---
title: "Projet"
author: "Groupe 6"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

library(dplyr)
library(readr)
library(sf)

seuil = 1000
```

# Traitement des données

## Importation des données de valeurs fonciaires

```{r warning=FALSE}
# Attention chemin vers les données possiblement à changer !!

dvf_19 <- read_csv("data/35_2019.csv", show_col_types = FALSE)
dvf_20 <- read_csv("data/35_2020.csv", show_col_types = FALSE)
dvf_21 <- read_csv("data/35_2021.csv", show_col_types = FALSE)
dvf_23 <- read_csv("data/35_2023.csv", show_col_types = FALSE)

dvf <- bind_rows(dvf_19, dvf_20, dvf_21, dvf_23)
dvf <- dvf[,-c(3,6:10,13:30, 34:38)]
# Suppression des colonnes inutiles

dvf <- dvf %>%
  filter(!is.na(longitude), !is.na(latitude), !is.na(valeur_fonciere))

dvf$type_local <- as.factor(dvf$type_local)

rm(dvf_19, dvf_20, dvf_21, dvf_23)
```

Traitement du fichier pour conserver uniquement les données qui nous intéressent

```{r}
dvf$type_local <- as.factor(dvf$type_local)
dvf$nature_mutation <- as.factor(dvf$nature_mutation)

dvf <- st_as_sf(dvf, coords = c("longitude", "latitude"), crs = 4326) 

dvf$date_mutation <- substr(dvf$date_mutation, 1, 4)

dvf <- dvf %>% 
  filter(code_commune %in% c(35238, 35051, 35281)) %>% 
  filter(nature_mutation %in% c("Vente")) %>% 
  filter(type_local  %in% c("Appartement", "Maison"))

dvf$code_commune <- as.factor(dvf$code_commune)

dvf <- dvf[!duplicated(dvf),-3 ]
# Suppression des doublons
dvf <- st_transform(dvf, crs = 2154)

summary(dvf)
```

# Création des groupes traités et de controles

```{r}
convert_to_decimal <- function(coord) {
  # Extraire les degrés, minutes, et secondes
  dms <- strsplit(coord, "°|′|″")[[1]]
  degrees <- as.numeric(dms[1])
  minutes <- as.numeric(dms[2])
  seconds <- as.numeric(dms[3])
  
  # Vérifier si la coordonnée est Ouest ou Sud (doit être négative)
  if (grepl("O|S", coord)) {
    sign <- -1
  } else {
    sign <- 1
  }
  
  # Calculer la valeur en degrés décimaux
  sign * (degrees + minutes / 60 + seconds / 3600)
}

metro <- data.frame(
  station = c("Saint-Jacques - Gaîté", "La Courrouze", "Cleunay", "Mabilais", "Colombier",
              "Gares", "Saint-Germain", "Sainte-Anne", "Jules Ferry", "Gros-Chêne", 
              "Les Gayeulles", "Joliot-Curie - Chateaubriand", "Beaulieu - Université",
              "Atalante", "Cesson - Viasilva"),
  
  latitude = c("48°05′31″ N", "48°05′47″ N", "48°06′03″ N", "48°06′18″ N", "48°06′21″ N",
               "48°06′14″ N", "48°06′38″ N", "48°06′52″ N", "48°07′07″ N", "48°07′30″ N",
               "48°07′46″ N", "48°07′27″ N", "48°07′20″ N", "48°07′38″ N", "48°07′54″ N"),
  
  longitude = c("1°42′13″ O", "1°41′54″ O", "1°42′23″ O", "1°41′34″ O", "1°40′55″ O",
                "1°40′20″ O", "1°40′34″ O", "1°40′49″ O", "1°40′15″ O", "1°39′52″ O",
                "1°39′26″ O", "1°39′05″ O", "1°38′22″ O", "1°37′41″ O", "1°37′12″ O")
)

metro <- metro %>%
  mutate(
    longitude = sapply(longitude, convert_to_decimal),
    latitude = sapply(latitude, convert_to_decimal)
  )

# Créer un objet sf à partir du dataframe
metro <- metro %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  st_transform(crs = 2154)

buffer_metro <- st_buffer(metro, dist = units::set_units(seuil, m))

dvf <- dvf %>%
  mutate(
    traite = st_intersects(dvf, buffer_metro, sparse = FALSE) %>% apply(1, any),
    
    nearest_metro_distance = st_distance(geometry, metro[st_nearest_feature(geometry, metro), ], by_element = TRUE) %>%
      as.numeric(),  # Convertir en mètres (évite les unités 'units')
    
    prix_m2 = valeur_fonciere/surface_reelle_bati
  ) %>% 
  filter(id_mutation != "2023-488844" & id_mutation != "2021-596462" & id_mutation != "2021-595984")

# Ind dont la distance est très éloignée

inf <- quantile(dvf$prix_m2, 0.05, na.rm = TRUE)
sup <- quantile(dvf$prix_m2, 0.95, na.rm = TRUE)

dvf <- dvf %>% filter(sup >= prix_m2 & prix_m2 >= inf)
```

