---
title: "Projet"
author: "BENOLIEL"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

# Traitement des données

## Importation des données de valeurs fonciaires

```{r warning=FALSE}
library(dplyr)
library(readr)
library(sf)

dvf_21 <- read_csv("data/35_2021.csv", show_col_types = FALSE)
# problems(dvf_21)
# -> Quelques erreurs de complétion pour certaines colonnes mais négligeables
dvf_23 <- read_csv("data/35_2023.csv", show_col_types = FALSE)

dvf <- bind_rows(dvf_21, dvf_23)
dvf <- dvf[,-c(3,6:10,13:30, 34:38)]
# Suppression des colonnes inutiles

dvf <- dvf %>%
  filter(!is.na(longitude), !is.na(latitude), !is.na(valeur_fonciere))

dvf$type_local <- as.factor(dvf$type_local)

rm(dvf_21, dvf_23)
```

Traitement du fichier pour conserver uniquement les données qui nous intéressent

```{r}
dvf$type_local <- as.factor(dvf$type_local)
dvf$code_commune <- as.factor(dvf$code_commune)
dvf$nature_mutation <- as.factor(dvf$nature_mutation)

dvf <- st_as_sf(dvf, coords = c("longitude", "latitude"), crs = 4326) 

dvf$date_mutation <- substr(dvf$date_mutation, 1, 4)

dvf <- dvf %>% 
  filter(code_commune %in% c(35238, 35051, 35281)) %>% 
  filter(nature_mutation %in% c("Vente")) %>% 
  filter(type_local  %in% c("Appartement", "Maison"))

dvf <- dvf[!duplicated(dvf),-3 ]
# Suppression des doublons

summary(dvf)
```

## Importation des données de filosofi

```{r}
filosofi <- st_read("data/carreaux_200m_met.shp")

filosofi <- filosofi[,-c(2,3,5)]

filosofi <- filosofi %>% filter(lcog_geo %in% 
                                  c(35238, 35051, 35281,
                                    3523835051, 3523835281,
                                    3505135238, 3528135238))
```

Jointure des données + Reprojection

```{r}
dvf <- st_transform(dvf, crs = 2154)
dvf <- st_join(dvf, filosofi, join = st_intersects)

dvf <- dvf %>%
  filter(!is.na(i_est_200))

summary(dvf)
rm(filosofi)
```

# Création des groupes traités et de controles

```{r}
convert_to_decimal <- function(coord) {
  # Extraire les degrés, minutes, et secondes
  dms <- strsplit(coord, "°|′|″")[[1]]
  degrees <- as.numeric(dms[1])
  minutes <- as.numeric(dms[2])
  seconds <- as.numeric(dms[3])
  
  # Vérifier si la coordonnée est Ouest ou Sud (doit être négative)
  if (grepl("O|S", coord)) {
    sign <- -1
  } else {
    sign <- 1
  }
  
  # Calculer la valeur en degrés décimaux
  sign * (degrees + minutes / 60 + seconds / 3600)
}

metro <- data.frame(
  station = c("Saint-Jacques - Gaîté", "La Courrouze", "Cleunay", "Mabilais", "Colombier",
              "Gares", "Saint-Germain", "Sainte-Anne", "Jules Ferry", "Gros-Chêne", 
              "Les Gayeulles", "Joliot-Curie - Chateaubriand", "Beaulieu - Université",
              "Atalante", "Cesson - Viasilva"),
  
  latitude = c("48°05′31″ N", "48°05′47″ N", "48°06′03″ N", "48°06′18″ N", "48°06′21″ N",
               "48°06′14″ N", "48°06′38″ N", "48°06′52″ N", "48°07′07″ N", "48°07′30″ N",
               "48°07′46″ N", "48°07′27″ N", "48°07′20″ N", "48°07′38″ N", "48°07′54″ N"),
  
  longitude = c("1°42′13″ O", "1°41′54″ O", "1°42′23″ O", "1°41′34″ O", "1°40′55″ O",
                "1°40′20″ O", "1°40′34″ O", "1°40′49″ O", "1°40′15″ O", "1°39′52″ O",
                "1°39′26″ O", "1°39′05″ O", "1°38′22″ O", "1°37′41″ O", "1°37′12″ O")
)

metro <- metro %>%
  mutate(
    longitude = sapply(longitude, convert_to_decimal),
    latitude = sapply(latitude, convert_to_decimal)
  )

# Créer un objet sf à partir du dataframe
metro <- metro %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  st_transform(dvf, crs = 2154)

buffer_metro <- st_buffer(metro, dist = units::set_units(1000, m))

dvf <- dvf %>%
  mutate(
    traite = st_intersects(dvf, buffer_metro, sparse = FALSE) %>% apply(1, any),
    
    nearest_metro_distance = st_distance(geometry, metro[st_nearest_feature(geometry, metro), ], by_element = TRUE) %>%
      as.numeric(),  # Convertir en mètres (évite les unités 'units')
    
    prix_m2 = valeur_fonciere/surface_reelle_bati
  )

inf <- quantile(dvf$prix_m2, 0.05, na.rm = TRUE)
sup <- quantile(dvf$prix_m2, 0.95, na.rm = TRUE)

dvf <- dvf %>% filter(sup >= prix_m2 & prix_m2 >= inf) %>% filter(id_mutation != "2023-488844")

table(dvf$date_mutation)
table(dvf$date_mutation, dvf$traite)

summary(dvf)
```


```{r}
library(mapview)
library(webshot)
library(htmlwidgets)

map_metro <- mapview(
  dvf %>% filter(date_mutation == 2023 & traite == FALSE),
  layer.name = "Groupe Contrôle (2023)",
  col.regions = "blue",  # Bleu pour le groupe contrôle
  cex = 3,  # Ajuste la taille des points
  homebutton = FALSE
) + 
  mapview(
    dvf %>% filter(date_mutation == 2023 & traite == TRUE),
    layer.name = "Groupe Traité (2023)",
    col.regions = "red",  # Rouge pour le groupe traité
    cex = 3,
    homebutton = FALSE
  )

map_metro

# Enregistrer la carte comme HTML
saveWidget(map_metro@map, "map_metro.html", selfcontained = TRUE)

# Convertir le fichier HTML en PNG
webshot("map_metro.html", file = "map_metro.png", vwidth = 1000, vheight = 800)
```



```{r}
library(leafsync)
library(leaflet.extras2)
library(classInt)
library(webshot2)

# Calcul des seuils avec la méthode de découpage souhaitée (par exemple, quantiles)
nb_classes <- 4  # Nombre de classes désirées

breaks <- classIntervals(
  dvf$valeur_fonciere, 
  n = nb_classes, 
  style = "quantile"
)$brks

# colorRampPalette(c("#FFF9E6", "#FFC300"))  # Jaune pâle -> Jaune vif

palette_custom <- colorRampPalette(c("#FFC300", "#286AC7")) 

map_21 <- mapview(dvf %>% filter(date_mutation==2021), 
                  layer.name = "2021",
                  zcol= "valeur_fonciere",
                  at = breaks,
                  col.regions = palette_custom,
                  homebutton = FALSE) + map_metro


map_23 <- mapview(dvf %>% filter(date_mutation==2023),
                  layer.name = "2023",
                  zcol= "valeur_fonciere",
                  at = breaks,
                  col.regions = palette_custom,
                  map.types = "CartoDB.Positron",
                  homebutton = FALSE) + map_metro

map_compa <- map_21 | map_23
#map_compa
#map_compa <- sync(map_21,map_23, ncol = 1)

mapshot(map_compa, url = "map.html")
```

```{r}
library(ggplot2)

ggplot(dvf, aes(x = nearest_metro_distance)) +
  geom_histogram(binwidth = 100 , color = "black", fill = "blue") +
  theme_bw()

mapview(dvf %>% filter(date_mutation==2023),
        layer.name = "2023 : la distance de la bouche de métro de ligne B la plus proche",
        zcol= "nearest_metro_distance",
        homebutton = FALSE)
```


```{r}
library(tidyverse)
df_long <- dvf %>%
  pivot_longer(cols = c(valeur_fonciere, surface_reelle_bati, nombre_pieces_principales, men_pauv, ind_snv, log_soc, prix_m2),
               names_to = "variable", values_to = "value")

# Créer un graphique avec facettes
ggplot(df_long, aes(x = traite, y = value, fill = traite, group = traite)) +
  geom_violin(adjust = 1L, scale = "area", width = 0.8) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9)) +
  scale_fill_hue(direction = 1) +
  theme_minimal() +
  facet_wrap(~ variable, scales = "free_y") +  # Facetter par variable avec échelle libre
  labs(x = "Treatment", y = "Value")
```

```{r}

A <- ggplot(data = dvf_1 %>% filter(date_mutation==2021)) + 
  geom_point(aes(x=nearest_metro_distance, y= prix_m2 , color= traite), alpha = 0.6) +
  theme_bw() +
  geom_smooth(aes(x = nearest_metro_distance, y = prix_m2), method = "lm", se = FALSE, color = "black") +
  geom_smooth(aes(x = nearest_metro_distance, y = prix_m2, color = traite), method = "lm", se = FALSE, linewidth = 2)
# Régressions conditionnelles par 'traite'

A
```