---
title: "Projet"
author: "BENOLIEL"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(stargazer)
library(dplyr)

stargazer(dvf, 
          type = "text", 
          title = "Statistiques descriptives",
          digits = 2,
          style = "aer")

trait <- dvf %>%  filter(date_mutation==2021) %>% group_split(traite)
for(i in seq_along(trait)) {
  cat("Annee 2021")
  stargazer(
    data.frame(trait[[i]]),
    type = "text", 
    title = paste("Statistiques descriptives pour le groupe", unique(trait[[i]]$traite)),
    summary = TRUE, 
    digits = 2
  )
}

```


# Cartographie / Graphique

## Visualisation des groupes traités et de contrôle en 2023

```{r}
library(mapview)
library(webshot)
library(htmlwidgets)

map <- mapview(
  dvf %>% filter(date_mutation == 2023 & traite == FALSE),
  layer.name = "Groupe Contrôle (2023)",
  col.regions = "#286AC7",  # Bleu pour le groupe contrôle
  cex = 3,  # Ajuste la taille des points
  homebutton = FALSE
) + 
  mapview(
    dvf %>% filter(date_mutation == 2023 & traite == TRUE),
    layer.name = "Groupe Traité (2023)",
    col.regions = "red",  # Rouge pour le groupe traité
    cex = 3,
    homebutton = FALSE
  ) +
  mapview(
    metro %>% select(-station),
    layer.name = "Bouche de métro",
    col.regions = "green",
    cex = 5,
    homebutton = FALSE
  )

map

# Enregistrer la carte comme HTML
saveWidget(map@map, "png/map_traite_controle_2023.html", selfcontained = TRUE)

# Convertir le fichier HTML en PNG
webshot("png/map_traite_controle_2023.html", file = "png/map_traite_controle_2023.png", 
        vwidth = 1000, vheight = 800, zoom = 2)
```

## Visualisation du prix au m2 en 2023

```{r}
library(classInt)

contour_aire_metro <- buffer_metro %>% 
  st_union() %>% 
  st_boundary() %>% 
  st_as_sf()

# Calcul des seuils avec la méthode de découpage souhaitée (par exemple, quantiles)
nb_classes <- 4  # Nombre de classes désirées

breaks <- classIntervals(
  dvf$prix_m2, 
  n = nb_classes, 
  style = "fisher"
)$brks

# colorRampPalette(c("#FFF9E6", "#FFC300"))  # Jaune pâle -> Jaune vif

palette_custom <- colorRampPalette(c("white", "#286AC7")) 


map <- mapview(dvf %>% filter(date_mutation==2023),
                  layer.name = "Prix au mètres carré en 2023",
                  zcol= "prix_m2",
                  at = breaks,
                  col.regions = palette_custom,
                  map.types = "CartoDB.Positron",
                  cex = 3,
                  homebutton = FALSE) + 
  mapview(contour_aire_metro, layer.name = "Séparation traité et contrôle",
          color = "red",          # Utiliser 'color' pour les lignes
          lwd = 3,
          homebutton = FALSE)

map

saveWidget(map@map, "png/map_prix_2023.html", selfcontained = TRUE)
webshot("png/map_prix_2023.html", file = "png/map_prix_2023.png", 
        vwidth = 1000, vheight = 800, zoom = 2)
```

## Visualisation du prix au m2 en 2021

```{r}
library(classInt)

contour_aire_metro <- buffer_metro %>% 
  st_union() %>% 
  st_boundary() %>% 
  st_as_sf()

# Calcul des seuils avec la méthode de découpage souhaitée (par exemple, quantiles)
nb_classes <- 4  # Nombre de classes désirées

breaks <- classIntervals(
  dvf$prix_m2, 
  n = nb_classes, 
  style = "fisher"
)$brks

# colorRampPalette(c("#FFF9E6", "#FFC300"))  # Jaune pâle -> Jaune vif

palette_custom <- colorRampPalette(c("white", "#286AC7")) 


map <- mapview(dvf %>% filter(date_mutation==2021),
                  layer.name = "Prix au mètres carré en 2021",
                  zcol= "prix_m2",
                  at = breaks,
                  col.regions = palette_custom,
                  map.types = "CartoDB.Positron",
                  cex = 3,
                  homebutton = FALSE) + 
  mapview(contour_aire_metro, layer.name = "Séparation traité et contrôle",
          color = "red",          # Utiliser 'color' pour les lignes
          lwd = 3,
          homebutton = FALSE)

map

saveWidget(map@map, "png/map_prix_2021.html", selfcontained = F)

webshot("png/map_prix_2021.html", file = "png/map_prix_2021.png", 
        vwidth = 1000, vheight = 800, zoom = 2)
```

## Distribution des distances au station de mètro B

```{r}
library(ggplot2)
dvf %>% filter(date_mutation %in% c(2021, 2023)) %>% 
  pull(nearest_metro_distance) %>% 
  quantile(0.5)

plot <- ggplot(dvf %>% filter(date_mutation %in% c(2021, 2023)), aes(x = nearest_metro_distance)) + 
  geom_histogram(aes(y = after_stat(count/sum(count))), binwidth = 300, color = "black", fill = "lightblue") + 
  geom_vline(xintercept = 1000, color = "black", linetype = "dashed", size = 1) +
  labs(y="Fréquence", x="Distance à la station de métro la plus proche") +
  theme_bw()

ggsave("png/histogram_distance_metro.png", plot = plot, width = 8, height = 6, dpi = 300)

```

## Comparaison des distributions des variables X

```{r}
library(tidyverse)

df_long <- dvf %>% 
  filter(date_mutation %in% c(2021, 2023)) %>% 
  pivot_longer(cols = c(valeur_fonciere, surface_reelle_bati, nombre_pieces_principales, prix_m2),
               names_to = "variable", values_to = "value")

plot <- ggplot(df_long %>% filter(date_mutation == 2021), aes(x = traite, y = value, fill = traite, group = traite)) +
  geom_violin(adjust = 1L, scale = "area", width = 0.8) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9)) +
  scale_fill_hue(direction = 1) +
  theme_bw() +
  facet_wrap(~ variable, scales = "free_y") +
  scale_fill_manual(values = c("FALSE" = "#286AC7", "TRUE" = "red"), labels = c("Non traité", "Traité")) +
  labs(x = "", y = "", fill="Groupe :")


ggsave("png/distrib_var_2021.png", plot = plot, width = 8, height = 6, dpi = 300)

plot <- ggplot(df_long %>% filter(date_mutation == 2023), aes(x = traite, y = value, fill = traite, group = traite)) +
  geom_violin(adjust = 1L, scale = "area", width = 0.8) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9)) +
  scale_fill_hue(direction = 1) +
  theme_bw() +
  facet_wrap(~ variable, scales = "free_y") +
  scale_fill_manual(values = c("FALSE" = "#286AC7", "TRUE" = "red"), labels = c("Non traité", "Traité")) +
  labs(x = "", y = "", fill="Groupe :")

ggsave("png/distrib_var_2023.png", plot = plot, width = 8, height = 6, dpi = 300)
```


```{r}
mean_prix<- dvf %>%
  group_by(date_mutation, traite) %>%
  summarise(mean_prix = mean(prix_m2, na.rm = TRUE))

plot <- ggplot(mean_prix, aes(x = date_mutation, y = mean_prix, color = traite, group = traite)) +
  geom_point(size = 3) +  # Ajout des points
  geom_line(size = 1) +   # Ajout des lignes pour relier les points
  scale_color_manual(values = c("FALSE" = "#286AC7", "TRUE" = "red"), labels = c("Non traité", "Traité")) +
  labs(
    title = "",
    x = "Période",
    y = "Prix au m²",
    color = "Groupe :"
  ) +
  theme_bw()

ggsave("png/moy_prix.png", plot = plot, width = 8, height = 6, dpi = 300)

```

